services:
  alterbot:
    container_name: alterbot
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - config:/usr/src/bot/config
      - data:/usr/src/bot/data
    env_file: ./.env
volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind