services:
  alterbot:
    container_name: alterbot
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - config.json:/usr/src/bot/config.json
    env_file: ./.env